import 'package:chi_application/models/cars_model.dart';

class CarRepository {
  List getAll() => _cars;

  List _cars = [
    {
      "make": "Acura",
      "brand": [
        {"name": "CL", "category": "Coupe"},
        {"name": "ILX", "category": "Sedan"},
        {"name": "Integra", "category": "Sedan"},
        {"name": "Legend", "category": "Sedan"},
        {"name": "MDX", "category": "SUV"},
        {"name": "NSX", "category": "Coupe"},
        {"name": "RDX", "category": "SUV"},
        {"name": "RL", "category": "Sedan"},
        {"name": "RLX", "category": "Sedan"},
        {"name": "RSX", "category": "Coupe"},
        {"name": "SLX", "category": "SUV"},
        {"name": "TL", "category": "Sedan"},
        {"name": "TLX", "category": "Sedan"},
        {"name": "TSX", "category": "Sedan"},
        {"name": "Vigor", "category": "Sedan"},
        {"name": "ZDX", "category": "SUV"},
      ]
    },
    {
      "make": "Alfa Romeo",
      "brand": [
        {"name": "147", "category": "Sedan"},
        {"name": "164", "category": "Sedan"},
        {"name": "4C", "category": "Coupe"},
        {"name": "4C Spider", "category": "Convertible"},
        {"name": "Brera", "category": "Sedan"},
        {"name": "Giulia", "category": "Sedan"},
        {"name": "Giulietta", "category": "Sedan"},
        {"name": "GT", "category": "Sedan"},
        {"name": "Mito", "category": "Sedan"},
        {"name": "Stelvio", "category": "SUV"},
      ]
    },
    {
      "make": "Alhambra",
      "brand": [
        {"name": "Jeep", "category": "Coupe"},
      ]
    },
    {
      "make": "Aston Martin",
      "brand": [
        {"name": "DB11", "category": "Coupe"},
        {"name": "DB9", "category": "Coupe"},
        {"name": "DB9 Carbon Edition", "category": "Coupe"},
        {"name": "DB9 Volante", "category": "Coupe"},
        {"name": "DBS", "category": "Coupe"},
        {"name": "Rapide", "category": "Sedan"},
        {"name": "Rapide S", "category": "Coupe"},
        {"name": "V12 Vantage S", "category": "Coupe"},
        {"name": "V12 Vantage S Roadster", "category": "Convertible"},
        {"name": "V8 Vantage", "category": "Coupe"},
        {"name": "V8 Vantage Roadster", "category": "Convertible"},
        {"name": "V8 Vantage S Roadster", "category": "Coupe"},
        {"name": "Vantage N430", "category": "Coupe"},
        {"name": "Vanquish", "category": "Coupe"},
        {"name": "Vanquish Carbon Edition", "category": "Coupe"},
        {"name": "Vanquish Volante", "category": "Coupe"},
        {"name": "Virage", "category": "Coupe"},
      ]
    },
    {
      "make": "Audi",
      "brand": [
        {"name": "100", "category": "Sedan"},
        {"name": "80", "category": "Sedan"},
        {"name": "90", "category": "Sedan"},
        {"name": "A1", "category": "Sedan"},
        {"name": "A3", "category": "Wagon"},
        {"name": "A3 Cabriolet", "category": "Wagon"},
        {"name": "A3 Sportback e-tron", "category": "Wagon"},
        {"name": "A4", "category": "Sedan"},
        {"name": "A5", "category": "Coupe"},
        {"name": "A5 Cabriolet", "category": "Coupe"},
        {"name": "A5 Sport", "category": "Coupe"},
        {"name": "A6", "category": "Sedan"},
        {"name": "A7", "category": "Sedan"},
        {"name": "A8", "category": "Sedan"},
        {"name": "AB L", "category": "Sedan"},
        {"name": "AB L W12", "category": "Sedan"},
        {"name": "All Road", "category": "Sedan"},
        {"name": "Q1", "category": "SUV"},
        {"name": "Q2", "category": "SUV"},
        {"name": "Q3", "category": "SUV"},
        {"name": "Q4", "category": "SUV"},
        {"name": "Q5", "category": "SUV"},
        {"name": "Q5 Hybrid", "category": "SUV"},
        {"name": "Q6", "category": "SUV"},
        {"name": "Q7", "category": "SUV"},
        {"name": "Q8", "category": "SUV"},
        {"name": "Q9", "category": "SUV"},
        {"name": "Quattro", "category": "Sedan"},
        {"name": "R8", "category": "Coupe"},
        {"name": "R8 Spyder", "category": "Convertible"},
        {"name": "RS 3", "category": "Sedan"},
        {"name": "RS 4", "category": "Sedan"},
        {"name": "RS 5", "category": "Coupe"},
        {"name": "RS 5 Cabriolet", "category": "Coupe"},
        {"name": "RS 6", "category": "Sedan"},
        {"name": "RS 7", "category": "Sedan"},
        {"name": "S3", "category": "Sedan"},
        {"name": "S4", "category": "Sedan"},
        {"name": "S5", "category": "Sedan"},
        {"name": "S5 Cabriolet", "category": "Sedan"},
        {"name": "S6", "category": "Wagon"},
        {"name": "S7", "category": "Sedan"},
        {"name": "S8", "category": "Sedan"},
        {"name": "SQ5", "category": "SUV"},
        {"name": "TT", "category": "Coupe"},
        {"name": "TT Roadster", "category": "Convertible"},
        {"name": "TTS", "category": "Coupe"},
        {"name": "TTS Roadster", "category": "Convertible"},
      ]
    },
    {
      "make": "Bajaj",
      "brand": [
        {"name": "Motorcycle", "category": "Tricycle"},
        {"name": "Tricycle", "category": "Tricycle"},
      ]
    },
    {
      "make": "Baw",
      "brand": [
        {"name": "Truck", "category": "Truck"},
      ]
    },
    {
      "make": "Bredford",
      "brand": [
        {"name": "200", "category": "Truck"},
        {"name": "Lorry", "category": "Truck"},
      ]
    },
    {
      "make": "Bentley",
      "brand": [
        {"name": "Continental GT", "category": "Coupe"},
        {"name": "Continental GT Convertible", "category": "Convertible"},
        {"name": "Continental GT Coupe", "category": "Coupe"},
        {"name": "Continental GT Speed Coupe", "category": "Coupe"},
        {"name": "Continental GT V8 Coupe", "category": "Coupe"},
        {"name": "Continental GT V8 S Coupe", "category": "Coupe"},
        {"name": "Flying Spur", "category": "Sedan"},
        {"name": "Grand Convertible", "category": "Convertible"},
        {"name": "Mulsanne", "category": "Sedan"},
      ]
    },
    {
      "make": "BMW",
      "brand": [
        {"name": "1 Series 3-Door", "category": "Coupe"},
        {"name": "1 Series 5-Door", "category": "Coupe"},
        {"name": "1 Series Active", "category": "Coupe"},
        {"name": "2 Series Convertible", "category": "Convertible"},
        {"name": "2 Series Coupe", "category": "Coupe"},
        {"name": "2 Series Gran Tourer", "category": "Coupe"},
        {"name": "3 Series Gran Turismo", "category": "Sedan"},
        {"name": "3 Series Sedan", "category": "Sedan"},
        {"name": "3 Series Touring", "category": "Sedan"},
        {"name": "316", "category": "Sedan"},
        {"name": "318", "category": "Sedan"},
        {"name": "335I", "category": "Sedan"},
        {"name": "4 Series Convertible", "category": "Convertible"},
        {"name": "4 Series Coupe", "category": "Coupe"},
        {"name": "4 Series Gran Coupe", "category": "Coupe"},
        {"name": "5 Series Gran Turismo", "category": "Sedan"},
        {"name": "5 Series Sedan", "category": "Sedan"},
        {"name": "5 Series Touring", "category": "Sedan"},
        {"name": "528I", "category": "Sedan"},
        {"name": "6 Series Convertible", "category": "Convertible"},
        {"name": "6 Series Coupe", "category": "Coupe"},
        {"name": "6 Series Gran Coupe", "category": "Coupe"},
        {"name": "7 Series", "category": "Sedan"},
        {"name": "8 Series", "category": "Coupe"},
        {"name": "Active Hybrid 3", "category": "Coupe"},
        {"name": "Active Hybrid 5", "category": "Coupe"},
        {"name": "Active Hybrid 7", "category": "Coupe"},
        {"name": "I3", "category": "Sedan"},
        {"name": "I8", "category": "Sedan"},
        {"name": "M ", "category": "Coupe"},
        {"name": "M Convertible", "category": "Convertible"},
        {"name": "M2", "category": "Coupe"},
        {"name": "M3 Sedan", "category": "Sedan"},
        {"name": "M3 Convertible", "category": "Convertible"},
        {"name": "M4 Coupe", "category": "Coupe"},
        {"name": "M4 Convertible", "category": "Convertible"},
        {"name": "M5 Sedan", "category": "Sedan"},
        {"name": "M6 Convertible", "category": "Convertible"},
        {"name": "M6 Coupe", "category": "Coupe"},
        {"name": "M6 Gran Coupe", "category": "Coupe"},
        {"name": "X1", "category": "SUV"},
        {"name": "X2", "category": "SUV"},
        {"name": "X3", "category": "SUV"},
        {"name": "X4", "category": "SUV"},
        {"name": "X5", "category": "SUV"},
        {"name": "X5 M", "category": "SUV"},
        {"name": "X6", "category": "SUV"},
        {"name": "X6 M", "category": "SUV"},
        {"name": "X7", "category": "SUV"},
        {"name": "Z3", "category": "Coupe"},
        {"name": "Z3 Convertible", "category": "Convertible"},
        {"name": "Z4 Convertible", "category": "Convertible"},
        {"name": "Z4 Coupe", "category": "Coupe"},
      ]
    },
    {
      "make": "Brilliance",
      "brand": [
        {"name": "AUTO M1", "category": "Coupe"},
        {"name": "AUTO M2", "category": "Coupe"},
        {"name": "AUTO M3", "category": "Coupe"},
        {"name": "BS6", "category": "Coupe"},
        {"name": "FRV", "category": "Coupe"},
      ]
    },
    {
      "make": "Bristol",
      "brand": [
        {"name": "400", "category": "Coupe"},
        {"name": "401", "category": "Coupe"},
        {"name": "402", "category": "Coupe"},
        {"name": "403", "category": "Coupe"},
        {"name": "404", "category": "Coupe"},
        {"name": "405", "category": "Coupe"},
        {"name": "406", "category": "Coupe"},
        {"name": "407", "category": "Coupe"},
        {"name": "408", "category": "Coupe"},
        {"name": "409", "category": "Coupe"},
        {"name": "410", "category": "Coupe"},
        {"name": "411", "category": "Coupe"},
        {"name": "412", "category": "Coupe"},
        {"name": "603", "category": "Sedan"},
        {"name": "Beaufighter", "category": "Sedan"},
        {"name": "Blenhem", "category": "Sedan"},
        {"name": "Britannia", "category": "Sedan"},
        {"name": "Fighter", "category": "Sedan"},
      ]
    },
    {
      "make": "Bugatti",
      "brand": [
        {"name": "Bolide W16", "category": "Coupe"},
        {"name": "Centodieci W16", "category": "Coupe"},
        {"name": "Chiron W16", "category": "Coupe"},
        {"name": "Divo", "category": "Coupe"},
        {"name": "EB110", "category": "Coupe"},
        {"name": "Type 13", "category": "Coupe"},
        {"name": "Type 18 Garros", "category": "Coupe"},
        {"name": "Type 252", "category": "Coupe"},
        {"name": "Type 35", "category": "Coupe"},
        {"name": "Type 41 Royale", "category": "Coupe"},
        {"name": "Type 57", "category": "Coupe"},
        {"name": "Type 101", "category": "Coupe"},
        {"name": "Veyron EB16.4", "category": "Coupe"},
      ]
    },
    {
      "make": "Buick",
      "brand": [
        {"name": "Cascade", "category": "Convertible"},
        {"name": "Century", "category": "Sedan"},
        {"name": "Enclave Convenience Sport Utility", "category": "SUV"},
        {"name": "Enclave Leather Sport Utility", "category": "SUV"},
        {"name": "Enclave Premium Sport Utility", "category": "SUV"},
        {"name": "Encore Base Sport Utility", "category": "SUV"},
        {"name": "Encore Convenience Sport Utility", "category": "SUV"},
        {"name": "Encore Leather Sport Utility", "category": "SUV"},
        {"name": "Encore Premium Sport Utility", "category": "SUV"},
        {"name": "Envision", "category": "SUV"},
        {"name": "LaCrosse", "category": "Sedan"},
        {"name": "Lucerne", "category": "Sedan"},
        {"name": "LaCrosse", "category": "Sedan"},
        {"name": "Park Avenue", "category": "Sedan"},
        {"name": "Rainer", "category": "SUV"},
        {"name": "Regal", "category": "Sedan"},
        {"name": "Regal TourX", "category": "Wagon"},
        {"name": "Rendezvous", "category": "SUV"},
        {"name": "Riviera", "category": "Coupe"},
        {"name": "RoadMaster", "category": "Sedan"},
        {"name": "Skylark", "category": "Sedan"},
        {"name": "Terraza", "category": "Van"},
        {"name": "Verano", "category": "Sedan"},
      ]
    },
    {
      "make": "Cadillac",
      "brand": [
        {"name": "ATS Coupe", "category": "Coupe"},
        {"name": "ATS Sedan", "category": "Sedan"},
        {"name": "ATS -V", "category": "Sedan"},
        {"name": "ATS -V Coupe", "category": "Coupe"},
        {"name": "Allante", "category": "Convertible"},
        {"name": "Brougham", "category": "Sedan"},
        {"name": "CT4", "category": "Sedan"},
        {"name": "CT5", "category": "Sedan"},
        {"name": "CT6", "category": "Sedan"},
        {"name": "CT4 -V", "category": "Sedan"},
        {"name": "CTS Sedan", "category": "Sedan"},
        {"name": "CTS -V Coupe", "category": "Coupe"},
        {"name": "Catera", "category": "Sedan"},
        {"name": "DTS Sedan", "category": "Sedan"},
        {"name": "DeVille", "category": "Sedan"},
        {"name": "ELR", "category": "Coupe"},
        {"name": "Escalade ESV", "category": "SUV"},
        {"name": "Escalade EST Pickup Truck", "category": "Pickup"},
        {"name": "Escalade ESV Hybrid", "category": "SUV"},
        {"name": "Seville", "category": "Sedan"},
        {"name": "SRX", "category": "SUV"},
        {"name": "SRX Crossover", "category": "SUV"},
        {"name": "STS", "category": "Sedan"},
        {"name": "XLR Convertible", "category": "Convertible"},
        {"name": "XT4", "category": "SUV"},
        {"name": "XT5", "category": "SUV"},
        {"name": "XT6", "category": "SUV"},
        {"name": "XTS", "category": "Sedan"},
      ]
    },
    {
      "make": "Chery",
      "brand": [
        {"name": "Arrizo", "category": "Coupe"},
        {"name": "A3", "category": "Coupe"},
        {"name": "E5 Comfort", "category": "Coupe"},
        {"name": "QQ3", "category": "Coupe"},
        {"name": "Tiggo", "category": "Coupe"},
      ]
    },
    {
      "make": "Chevrolet",
      "brand": [
        {"name": "1500 Extended Cab Pickup", "category": "Pickup"},
        {"name": "1500 Regular Cab Pickup", "category": "Pickup"},
        {"name": "2500 Crew Cab Pickup", "category": "Pickup"},
        {"name": "2500 Extended Cab Pickup", "category": "Pickup"},
        {"name": "2500 HD Extended Cab Pickup", "category": "Pickup"},
        {"name": "2500 HD Regular Cab Pickup", "category": "Pickup"},
        {"name": "2500 Regular Cab Pickup", "category": "Pickup"},
        {"name": "3500 Crew Cab Pickup", "category": "Pickup"},
        {"name": "3500 Extended Cab Pickup", "category": "Pickup"},
        {"name": "3500 HD Extended Cab Pickup", "category": "Pickup"},
        {"name": "3500 HD Regular Cab Pickup", "category": "Pickup"},
        {"name": "3500 Regular Cab Pickup", "category": "Pickup"},
        {"name": "APV Cargo", "category": "Minivan"},
        {"name": "Astro Cargo", "category": "Minivan"},
        {"name": "Astro Passenger", "category": "Minivan"},
        {"name": "Avalanche", "category": "SUV"},
        {"name": "Avalanche 1500 Pickup", "category": "Pickup"},
        {"name": "Avalanche 2500 Pickup", "category": "Pickup"},
        {"name": "Aveo", "category": "Sedan"},
        {"name": "Beretta", "category": "Coupe"},
        {"name": "Blazer", "category": "SUV"},
        {"name": "Bolt EV", "category": "Hatchback"},
        {"name": "Camaro Coupe", "category": "Coupe"},
        {"name": "Camaro Convertible", "category": "Convertible"},
        {"name": "Caprice", "category": "Sedan"},
        {"name": "Captiva Sport", "category": "SUV"},
        {"name": "Cavalier", "category": "Sedan"},
        {"name": "City Express", "category": "Minivan"},
        {"name": "Classic", "category": "Sedan"},
        {"name": "Cobalt", "category": "Sedan"},
        {"name": "Colorado Crew Cab", "category": "Pickup"},
        {"name": "Colorado Extended Cab", "category": "Pickup"},
        {"name": "Colorado Regular Cab", "category": "Pickup"},
        {"name": "Corvette Coupe", "category": "Coupe"},
        {"name": "Corvette", "category": "Convertible"},
        {"name": "Cruze", "category": "Sedan"},
        {"name": "Equinox", "category": "SUV"},
        {"name": "Express 1500 Cargo", "category": "Minivan"},
        {"name": "Express 1500 Passenger", "category": "Minivan"},
        {"name": "Express 2500 Cargo", "category": "Minivan"},
        {"name": "Express 2500 Passenger", "category": "Minivan"},
        {"name": "Express 3500 Cargo", "category": "Minivan"},
        {"name": "Express 3500 Passenger", "category": "Minivan"},
        {"name": "G-Series 1500", "category": "Minivan"},
        {"name": "G-Series 2500", "category": "Minivan"},
        {"name": "G-Series 3500", "category": "Minivan"},
        {"name": "G-Series G10", "category": "Minivan"},
        {"name": "G-Series G20", "category": "Minivan"},
        {"name": "G-Series G30", "category": "Minivan"},
        {"name": "HHR", "category": "Wagon"},
        {"name": "Impala", "category": "Sedan"},
        {"name": "Lumina", "category": "Sedan"},
        {"name": "Lumina APV", "category": "Minivan"},
        {"name": "Lumina APV", "category": "Minivan"},
        {"name": "Lumina Passenger", "category": "Minivan"},
        {"name": "Malibu", "category": "Sedan"},
        {"name": "Metro", "category": "Sedan"},
        {"name": "Minibus", "category": "Minivan"},
        {"name": "Monte Carlo", "category": "Coupe"},
        {"name": "Prizm", "category": "Sedan"},
        {"name": "S10 Blazer", "category": "SUV"},
        {"name": "S10 Crew Cab", "category": "Pickup"},
        {"name": "S10 Extended Cab", "category": "Pickup"},
        {"name": "S10 Regular Cab", "category": "Pickup"},
        {"name": "Silverado (Classic) 1500 Crew Cab", "category": "Pickup"},
        {"name": "Silverado (Classic) 1500 Extended Cab", "category": "Pickup"},
        {"name": "Silverado (Classic) 1500 HD Crew Cab", "category": "Pickup"},
        {"name": "Silverado (Classic) 1500 Regular Cab", "category": "Pickup"},
        {"name": "Silverado (Classic) 2500 HD Crew Cab", "category": "Pickup"},
        {
          "name": "Silverado (Classic) 2500 HD Extended Cab",
          "category": "Pickup"
        },
        {
          "name": "Silverado (Classic) 2500 HD Regular Cab",
          "category": "Pickup"
        },
        {"name": "Silverado (Classic) 3500 Crew Cab", "category": "Pickup"},
        {"name": "Silverado (Classic) 3500 Extended Cab", "category": "Pickup"},
        {"name": "Silverado (Classic) 3500 Regular Cab", "category": "Pickup"},
        {"name": "Silverado 1500 Crew Cab", "category": "Pickup"},
        {"name": "Silverado 1500 Double Cab", "category": "Pickup"},
        {"name": "Silverado 1500 Extended Cab", "category": "Pickup"},
        {"name": "Silverado 1500 HD Crew Cab", "category": "Pickup"},
        {"name": "Silverado 1500 LD Double Cab", "category": "Pickup"},
        {"name": "Silverado 1500 Regular Cab", "category": "Pickup"},
        {"name": "Silverado 2500 Crew Cab", "category": "Pickup"},
        {"name": "Silverado 2500 Extended Cab", "category": "Pickup"},
        {"name": "Silverado 2500 HD Crew Cab", "category": "Pickup"},
        {"name": "Silverado 2500 HD Double Cab", "category": "Pickup"},
        {"name": "Silverado 2500 HD Extended Cab", "category": "Pickup"},
        {"name": "Silverado 2500 HD Regular Cab", "category": "Pickup"},
        {"name": "Silverado 2500 Regular Cab", "category": "Pickup"},
        {"name": "Silverado 3500 Crew Cab", "category": "Pickup"},
        {"name": "Silverado 3500 Extended Cab", "category": "Pickup"},
        {"name": "Silverado 3500 HD Crew Cab", "category": "Pickup"},
        {"name": "Silverado 3500 HD Double Cab", "category": "Pickup"},
        {"name": "Silverado 3500 HD Extended Cab", "category": "Pickup"},
        {"name": "Silverado 3500 HD Regular Cab", "category": "Pickup"},
        {"name": "Silverado 3500 Regular Cab", "category": "Pickup"},
        {"name": "Sonic", "category": "Sedan"},
        {"name": "Spark", "category": "Hatchback"},
        {"name": "Spark EV", "category": "Hatchback"},
        {"name": "Sportvan G10", "category": "Minivan"},
        {"name": "Suburban", "category": "SUV"},
        {"name": "Suburban 1500", "category": "SUV"},
        {"name": "Suburban 2500", "category": "SUV"},
        {"name": "Suburban 3500HD", "category": "SUV"},
        {"name": "SS", "category": "SUV"},
        {"name": "Tahoe", "category": "SUV"},
        {"name": "Tracker", "category": "SUV"},
        {"name": "TrailBlazer", "category": "SUV"},
        {"name": "Traverse", "category": "SUV"},
        {"name": "Trax", "category": "SUV"},
        {"name": "Uplander Cargo", "category": "Minivan"},
        {"name": "Uplander Passenger", "category": "Minivan"},
        {"name": "Venture Cargo", "category": "Minivan"},
        {"name": "Volt", "category": "Sedan"},
      ]
    },
    {
      "make": "Chrysler",
      "brand": [
        {"name": "1500", "category": "Minivan"},
        {"name": "200", "category": "Sedan"},
        {"name": "200 Convertible", "category": "Convertible"},
        {"name": "200 Touring Convertible", "category": "Convertible"},
        {"name": "2500", "category": "Pickup"},
        {"name": "300", "category": "Sedan"},
        {"name": "300C", "category": "Sedan"},
        {"name": "300M", "category": "Sedan"},
        {"name": "3500", "category": "Pickup"},
        {"name": "4500", "category": "Pickup"},
        {"name": "5500", "category": "Pickup"},
        {"name": "Aspen Hybrid", "category": "SUV"},
        {"name": "Cirrus", "category": "Sedan"},
        {"name": "Concrode", "category": "Sedan"},
        {"name": "Delta Coupe", "category": "Coupe"},
        {"name": "Fifth Ave", "category": "Sedan"},
        {"name": "Grand Voyager", "category": "Van"},
        {"name": "Imperial", "category": "Sedan"},
        {"name": "LHS", "category": "Sedan"},
        {"name": "LeBaron Sedan", "category": "Sedan"},
        {"name": "LeBaron Convertible", "category": "Convertible"},
        {"name": "Nassau", "category": "Sedan"},
        {"name": "New Yorker", "category": "Sedan"},
        {"name": "PT Cruiser", "category": "Wagon"},
        {"name": "Pacifica", "category": "Wagon"},
        {"name": "Prowler", "category": "Convertible"},
        {"name": "Sebring", "category": "Sedan"},
        {"name": "Sebring Convertible", "category": "Convertible"},
        {"name": "Stratus", "category": "Sedan"},
        {"name": "Town & Country", "category": "Van"},
        {"name": "Viper", "category": "Sedan"},
        {"name": "Voyager", "category": "Minivan"},
        {"name": "Ypsilon", "category": "Sedan"},
      ]
    },
    {
      "make": "Citroen",
      "brand": [
        {"name": "2.5A T.D", "category": "Coupe"},
        {"name": "Berlingo", "category": "Van"},
        {"name": "C4 Cactus", "category": "SUV"},
        {"name": "C4 New Range", "category": "SUV"},
        {"name": "C4 Picasso", "category": "SUV"},
        {"name": "C4 Cactus", "category": "SUV"},
        {"name": "C5 Saloon", "category": "SUV"},
        {"name": "C5 Tourer", "category": "SUV"},
        {"name": "Citroen C8", "category": "Van"},
        {"name": "Dispatch", "category": "Van"},
        {"name": "Dispatch Combi", "category": "Van"},
        {"name": "DS 3", "category": "Hatchback"},
        {"name": "DS 3 Cabrio", "category": "Hatchback"},
        {"name": "DS 4", "category": "Hatchback"},
        {"name": "DS 5", "category": "Hatchback"},
        {"name": "Grand C4 Picasso", "category": "Van"},
        {"name": "Nemo", "category": "Van"},
        {"name": "New Relay", "category": "Van"},
        {"name": "Xsara", "category": "Hatchback"},
      ]
    },
    {
      "make": "Daewoo",
      "brand": [
        {"name": "Lanos", "category": "Sedan"},
        {"name": "Leganza", "category": "Sedan"},
        {"name": "Nubira", "category": "Sedan"},
        {"name": "Truck", "category": "Truck"},
      ]
    },
    {
      "make": "Daf",
      "brand": [
        {"name": "Lorry", "category": "Truck"},
        {"name": "Truck", "category": "Truck"},
      ]
    },
    {
      "make": "Datsun",
      "brand": [
        {"name": "Copen 1.3 Pearl", "category": "Coupe"},
        {"name": "Cross", "category": "Coupe"},
        {"name": "Cuore 1.0 Eco-Top", "category": "Coupe"},
        {"name": "Copen 1.0 SX", "category": "Coupe"},
        {"name": "Go", "category": "Coupe"},
        {"name": "Go Plus", "category": "Coupe"},
        {"name": "Gran Move", "category": "Coupe"},
        {"name": "Gran Move 1.5", "category": "Coupe"},
        {"name": "Materia 1.5", "category": "Coupe"},
        {"name": "Materia 1.5 4WD", "category": "Coupe"},
        {"name": "On Do", "category": "Coupe"},
        {"name": "Redi-Go", "category": "Coupe"},
        {"name": "Sirion", "category": "Coupe"},
        {"name": "Sirion 1.3", "category": "Coupe"},
        {"name": "Sirion 1.3 Eco-4WD", "category": "Coupe"},
        {"name": "Terios 1.3 16V 4X4", "category": "Coupe"},
        {"name": "Terios 1.3 16V 4X4 Trail", "category": "Coupe"},
        {"name": "Terios 1.3 16V SX 4WD", "category": "Coupe"},
        {"name": "Trevis", "category": "Coupe"},
        {"name": "Trevis 1.0", "category": "Coupe"},
        {"name": "YRV 1.3l 16V", "category": "Coupe"},
        {"name": "YRV 1.3l 16V 4X4", "category": "Coupe"},
      ]
    },
    {
      "make": "Dayun",
      "brand": [
        {"name": "1652 Step Van", "category": "Minivan"},
      ]
    },
    {
      "make": "Dodge",
      "brand": [
        {"name": "Avenger", "category": "Sedan"},
        {"name": "Caliber", "category": "Wagon"},
        {"name": "Caravan Cargo", "category": "Van"},
        {"name": "Caravan Passenger", "category": "Van"},
        {"name": "Challenger", "category": "Coupe"},
        {"name": "Charger", "category": "Coupe"},
        {"name": "Colt", "category": "Coupe"},
        {"name": "D150", "category": "Pickup"},
        {"name": "D250", "category": "Pickup"},
        {"name": "D350", "category": "Pickup"},
        {"name": "Dakota", "category": "Pickup"},
        {"name": "Dart", "category": "Pickup"},
        {"name": "Daytona", "category": "Sedan"},
        {"name": "Durango", "category": "Van"},
        {"name": "Grand Caravan", "category": "Van"},
        {"name": "Inrepid", "category": "Sedan"},
        {"name": "Journey", "category": "SUV"},
        {"name": "Magnum", "category": "Wagon"},
        {"name": "Inrepid", "category": "Sedan"},
        {"name": "Monaco", "category": "Sedan"},
        {"name": "Neon", "category": "Sedan"},
        {"name": "Nitro", "category": "SUV"},
        {"name": "RAM Pickup 1500", "category": "Pickup"},
        {"name": "RAM Pickup 2500", "category": "Pickup"},
        {"name": "RAM Pickup 3500", "category": "Pickup"},
        {"name": "RAM Van 1500", "category": "Van"},
        {"name": "RAM Van 2500", "category": "Van"},
        {"name": "RAM Van 3500", "category": "Van"},
        {"name": "RAM Wagon 1500", "category": "Van"},
        {"name": "RAM Wagon 2500", "category": "Van"},
        {"name": "RAM Wagon 3500", "category": "Van"},
        {"name": "Ramcharger", "category": "SUV"},
        {"name": "Sprinter 1500", "category": "Van"},
        {"name": "Sprinter 2500", "category": "Van"},
        {"name": "Sprinter 3500", "category": "Van"},
        {"name": "Stealth", "category": "Hatchback"},
        {"name": "Stratus", "category": "Sedan"},
        {"name": "Viper", "category": "Coupe"},
        {
          "name": "Viper SRT10 Roadster Final Edition",
          "category": "Convertible"
        },
      ]
    },
    {
      "make": "Eagle",
      "brand": [
        {"name": "Talon", "category": "Hatchback"},
        {"name": "Vision", "category": "Sedan"},
      ]
    },
    {
      "make": "Ferrari",
      "brand": [
        {"name": "430 Scuderia", "category": "Coupe"},
        {"name": "458 Italia", "category": "Coupe"},
        {"name": "458 Speciale", "category": "Coupe"},
        {"name": "458 Spider", "category": "Convertible"},
        {"name": "488 GTB", "category": "Coupe"},
        {"name": "488 Spider", "category": "Convertible"},
        {"name": "599 GTB Fiorano", "category": "Coupe"},
        {"name": "599 GTO", "category": "Coupe"},
        {"name": "612 Scaglietti", "category": "Coupe"},
        {"name": "California", "category": "Convertible"},
        {"name": "F12berlinetta", "category": "Coupe"},
        {"name": "F430", "category": "Coupe"},
        {"name": "FF", "category": "Coupe"},
        {"name": "FF458 Spider", "category": "Convertible"},
        {"name": "GTC4Lusso", "category": "Hatchback"},
        {"name": "LA Ferrari", "category": "Coupe"},
        {"name": "T458 Speciale", "category": "Coupe"},
      ]
    },
    {
      "make": "Fiat",
      "brand": [
        {"name": "124 Spider", "category": "Convertible"},
        {"name": "500 4-Door", "category": "Coupe"},
        {"name": "500 Cabrio", "category": "Coupe"},
        {"name": "500 Crossover", "category": "Coupe"},
        {"name": "500 Electric", "category": "Coupe"},
        {"name": "500 Hatchback", "category": "Coupe"},
        {"name": "Abarth", "category": "Coupe"},
        {"name": "Doblo", "category": "Van"},
        {"name": "Ducato", "category": "Van"},
        {"name": " Fiat Ducato", "category": "Van"},
        {"name": "Panda", "category": "Coupe"},
        {"name": "Panda 4A-4", "category": "Coupe"},
        {"name": "Panda Crossover", "category": "Coupe"},
        {"name": "Punto", "category": "Coupe"},
        {"name": "Qubo", "category": "Coupe"},
        {"name": "Stilo", "category": "Coupe"},
      ]
    },
    {
      "make": "Ford",
      "brand": [
        {"name": "Aerostar", "category": "Van"},
        {"name": "Aspire", "category": "Hatchback"},
        {"name": "Bronco", "category": "SUV"},
        {"name": "C-MAX Energi", "category": "Wagon"},
        {"name": "C-MAX Hybrid", "category": "Wagon"},
        {"name": "Club Wagon", "category": "Van"},
        {"name": "Contour", "category": "Sedan"},
        {"name": "Crown Victoria", "category": "Sedan"},
        {"name": "E150", "category": "Pickup"},
        {"name": "E250", "category": "Pickup"},
        {"name": "E350", "category": "Pickup"},
        {"name": "Econovan", "category": "Van"},
        {"name": "Edge", "category": "SUV"},
        {"name": "Escape", "category": "SUV"},
        {"name": "Escort", "category": "Sedan"},
        {"name": "Everest", "category": "Sedan"},
        {"name": "Excursion", "category": "SUV"},
        {"name": "Expendition", "category": "SUV"},
        {"name": "Expendition EL", "category": "SUV"},
        {"name": "Explorer", "category": "SUV"},
        {"name": "F-150", "category": "Pickup"},
        {"name": "F-250", "category": "Pickup"},
        {"name": "F-350", "category": "Pickup"},
        {"name": "F-450", "category": "Pickup"},
        {"name": "Festiva", "category": "Hatchback"},
        {"name": "Fiesta", "category": "Hatchback"},
        {"name": "Fiesta Review", "category": "Hatchback"},
        {"name": "Five Hundred", "category": "Sedan"},
        {"name": "Flex", "category": "SUV"},
        {"name": "Focus", "category": "Sedan"},
        {"name": "Focus ST", "category": "Hatchback"},
        {"name": "Freestar", "category": "Van"},
        {"name": "Freestyle", "category": "SUV"},
        {"name": "F-Series", "category": "Pickup"},
        {"name": "Fusion", "category": "Sedan"},
        {"name": "Fusion Energi", "category": "Sedan"},
        {"name": "Ford Galaxy", "category": "Van"},
        {"name": "Mondeo", "category": "Sedan"},
        {"name": "Mustang", "category": "Coupe"},
        {"name": "Mustang Convertible", "category": "Convertible"},
        {"name": "Ranger", "category": "Pickup"},
        {"name": "Shelby GT500 Convertible", "category": "Convertible"},
        {"name": "Shelby GT500 Coupe", "category": "Coupe"},
        {"name": "Super duty", "category": "Pickup"},
        {"name": "Taurus", "category": "Sedan"},
        {"name": "Tempo", "category": "Sedan"},
        {"name": "Thunderbird", "category": "Coupe"},
        {"name": "Transit E150", "category": "Van"},
        {"name": "Transit 250", "category": "Van"},
        {"name": "Transit 350", "category": "Van"},
        {"name": "Windstar", "category": "Van"},
      ]
    },
  ];

  getBrands(String make) async {
    await Future.delayed(Duration(seconds: 4), () {
      print('Future.delayed');
    });

    return Future.value(_cars
        .map((map) => CarsModel.fromJSON(map))
        .where((item) => item.make == make)
        .map((e) => e.brand.map((e) => e.name))
        .expand((i) => i)
        .toList());
  }

  getCategory(String make) async {
    await Future.delayed(Duration(seconds: 3), () {
      print('Future.delayed');
    });

    return Future.value(_cars
        .map((map) => CarsModel.fromJSON(map))
        .where((item) => item.make == make)
        .map((e) => e.brand.map((e) => e.category))
        .expand((i) => i)
        .toList());
  }

  List<String> getMakes() => _cars
      .map((map) => CarsModel.fromJSON(map))
      .map((item) => item.make)
      .toList();
}
